#!/bin/bash
# Program:
# 	This program is for function testing.
# History:
# 	2016/04/13	Thank	first release

echo "<<show>>"
function show(){
	echo "function name : ${0}"
	echo "function args : ${1} ${2} ${3} ${4}"
}
show "one" "two" "three"

echo "<<info and error>>"
function info() {
	date=$(date +"%Y/%m/%d %H:%M:%S")
	echo "${date} ${@}" 
}
function error() {
	date=$(date +"%Y/%m/%d %H:%M:%S")
	echo "${date} ${@}" 1>&2
}

exit 0