#!/bin/bash
# Program:
# 	This program is for function testing.
# History:
# 	2016/04/13	Thank	first release

echo "<<show>>"
function show(){
	echo "function name : ${0}"
	echo "function args : ${1} ${2} ${3} ${4}"
}
show "one" "two" "three"

echo "<<info>>"
function info() {
	date=$(date +"%Y/%m/%d %H:%M:%S")
	echo "${date} ${@}" 
}
info "this" "is" "info"

echo "<<error>>"
function error() {
	date=$(date +"%Y/%m/%d %H:%M:%S")
	echo "${date} ${@}" 1>&2
}
error "this" "is" "error"

echo "<<execute script>>"
function executeScript() {
	"/bin/ls" "${@}"
	returnCode=$?
	echo ${returnCode}
}
executeScript "/tmp"

exit 0