#!/bin/bash
# Program:
# 	This program is for testing.
# History:
# 	2016/04/13	Thank	first release

# test
file_0=~/.bashrc
file_1=/etc/passwd

if test -e ${file_0}; then
	echo "file exists."
else
	echo "file not exists."
fi

if test -f ${file_0}; then
	echo "is file."
else
	echo "is not file."
fi

if test -d ${file_0}; then
	echo "is directory."
else
	echo "is not directory."
fi

if test -b ${file_0}; then
	echo "is block device."
else
	echo "is not block device."
fi

if test -c ${file_0}; then
	echo "is character device."
else
	echo "is not character device."
fi

if test -S ${file_0}; then
	echo "is socket file."
else
	echo "is not socket file."
fi

if test -p ${file_0}; then
	echo "is pipe."
else
	echo "is not pipe."
fi

if test -L ${file_0}; then
	echo "is link file."
else
	echo "is not link file."
fi

if test -r ${file_0}; then
	echo "is readable."
else
	echo "is not readable."
fi

if test -w ${file_0}; then
	echo "is writable."
else
	echo "is not writable."
fi

if test -x ${file_0}; then
	echo "is executable."
else
	echo "is not executable."
fi

if test -u ${file_0}; then
	echo "has SUID."
else
	echo "has no SUID."
fi

if test -g ${file_0}; then
	echo "has SGID."
else
	echo "has no SGID."
fi

if test -k ${file_0}; then
	echo "has sticky bit."
else
	echo "has no sticky bit."
fi

if test -s ${file_0}; then
	echo "is empty file."
else
	echo "is not empty file."
fi

if test ${file_0} -nt ${file_1}; then
	echo "${file_0} newer than ${file_1}"
else
	echo "${file_0} not newer than ${file_1}"
fi

if test ${file_0} -ot ${file_1}; then
	echo "${file_0} older than ${file_1}"
else
	echo "${file_0} not older than ${file_1}"
fi

if test ${file_0} -ef ${file_1}; then
	echo "${file_0} and ${file_1} is the same file."
else
	echo "${file_0} and ${file_1} is not the same file."
fi

exit 0